alias tmux-chat="bash ~/dotfiles/scripts/chat.sh"
alias tmux-lifeautomation="bash ~/dotfiles/scripts/lifeautomation.sh"
alias tmux-backup="bash ~/dotfiles/scripts/backup.sh"
alias connect-tyrion="ssh nick@192.168.50.29"
alias connect-walle="ssh walle@192.168.50.93"
alias connect-ada="ssh nick@192.168.50.247"
alias connect-karo="ssh karo@192.168.1.207"
alias extract-audio="bash ~/dotfiles/scripts/extract-audio.sh"
alias ytdlp="bash ~/dotfiles/scripts/ytdlp.sh"

alias whisperenv="source /home/ada/Sites/whisperer/whisper-env/bin/activate" #TODO: Hardcoded. Boo
